import { useRef, useState } from "react"
import { flushSync } from "react-dom"
import { getTheme, setTheme } from "../lib/theme-mode.js"

/* Sun disc and moon crescent are morph-compatible — both M + 5 cubics + Z
 * with corresponding anchors (generated by scripts/gen-sun-moon-paths.mjs).
 * The disc's `d` attribute below is the light state; index.css tweens it to
 * the crescent in dark mode via the CSS `d` property, while the rays swirl
 * out and the icon tilts. MOON also feeds the opacity-crossfade fallback for
 * browsers that can't animate `d`. */
const SUN_DISC =
  "M16.333 12.766C16.001 14.643 14.498 16.093 12.611 16.357C10.723 16.622 8.88 15.641 8.045 13.927C7.21 12.214 7.573 10.157 8.945 8.834C10.316 7.51 12.384 7.22 14.067 8.116C15.75 9.011 16.665 10.889 16.333 12.766Z"
const MOON =
  "M18.893 13.218C18.275 16.715 15.137 19.195 11.592 18.988C8.047 18.781 5.219 15.953 5.012 12.408C4.805 8.863 7.285 5.725 10.782 5.107C10.083 7.403 10.706 9.899 12.404 11.596C14.101 13.294 16.597 13.917 18.893 13.218Z"

const RAY_ANGLES = [0, 45, 90, 135, 180, 225, 270, 315]

export function ThemeToggle() {
  const btnRef = useRef(null)
  const fadeTimer = useRef(0)
  const [mode, setMode] = useState(getTheme)
  const dark = mode === "dark"

  function toggle() {
    // Derive the next theme from the DOM at apply time, not from render-time
    // state: with view transitions the flip runs async after the old-frame
    // snapshot, and a second click in that window would otherwise compute the
    // same `next` twice instead of toggling back.
    const apply = () => {
      const next = document.documentElement.dataset.theme === "dark" ? "light" : "dark"
      setTheme(next)
      flushSync(() => setMode(next))
    }

    const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches
    if (reduceMotion || typeof document.startViewTransition !== "function") {
      // No view transitions: crossfade every color for one beat instead.
      const root = document.documentElement
      if (!reduceMotion) {
        window.clearTimeout(fadeTimer.current)
        root.classList.add("theme-fade")
        fadeTimer.current = window.setTimeout(() => root.classList.remove("theme-fade"), 500)
      }
      apply()
      return
    }

    // Ripple: snapshot the old theme, apply the new one, then reveal it
    // inside a circle growing from the button to the farthest viewport corner.
    const rect = btnRef.current.getBoundingClientRect()
    const x = rect.left + rect.width / 2
    const y = rect.top + rect.height / 2
    const radius = Math.hypot(
      Math.max(x, window.innerWidth - x),
      Math.max(y, window.innerHeight - y),
    )

    const vt = document.startViewTransition(apply)
    vt.ready
      .then(() => {
        document.documentElement.animate(
          {
            clipPath: [
              `circle(0px at ${x}px ${y}px)`,
              `circle(${radius}px at ${x}px ${y}px)`,
            ],
          },
          {
            duration: 600,
            easing: "cubic-bezier(0.22, 1, 0.36, 1)",
            pseudoElement: "::view-transition-new(root)",
          },
        )
      })
      .catch(() => { /* transition skipped (rapid clicks) — theme is already applied */ })
  }

  return (
    <button
      ref={btnRef}
      type="button"
      className="theme-toggle"
      onClick={toggle}
      aria-label={dark ? "Switch to light theme" : "Switch to dark theme"}
      title={dark ? "Switch to light theme" : "Switch to dark theme"}
    >
      <svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true">
        <g className="tt-rays" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round">
          {RAY_ANGLES.map((deg) => {
            const a = (deg * Math.PI) / 180
            return (
              <line
                key={deg}
                x1={+(12 + 6.3 * Math.cos(a)).toFixed(3)}
                y1={+(12 + 6.3 * Math.sin(a)).toFixed(3)}
                x2={+(12 + 7.7 * Math.cos(a)).toFixed(3)}
                y2={+(12 + 7.7 * Math.sin(a)).toFixed(3)}
              />
            )
          })}
        </g>
        <path className="tt-disc" d={SUN_DISC} fill="currentColor" />
        <path className="tt-moon-fallback" d={MOON} fill="currentColor" />
      </svg>
    </button>
  )
}
